---
name: 'metaconfig'
---

SiteTree:
  extensions:
    - MetaManagerExtension

SiteConfig:
  extensions:
    - MetaConfigSiteConfigExtension

Page:
  extensions:
    - MetaConfigPageExtension

Security:
  extensions:
    - MetaConfigPageExtension